name: spacex_api_dart
description: The project of the empty template with Flutter has built the basic framework to realize the functions of internationalization, theme peeling etc.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  api:
    path: api
  core:
    path: core
  flutter_bloc: ^8.0.1
  bloc: 8.1.0
  logger: ^1.1.0
  equatable: ^2.0.3
  google_fonts: ^2.3.1
  effective_dart: ^1.3.2
  path_provider: ^2.0.11

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.2.0
  lint: ^1.8.2
  mockito: ^5.1.0
  bloc_test: ^9.0.3
  flutter_lints: 2.0.1
  mocktail: ^0.3.0
  dart_code_metrics: ^4.14.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
