name: data
description: A data module.
version: 1.0.0+1
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dio: ^5.0.3
  equatable: ^2.0.5
  freezed_annotation: 2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  retrofit: ^4.0.1
  stack_trace: ^1.11.0

dev_dependencies:
  build_runner: 2.3.3
  coverage: ^1.6.1
  dart_code_metrics: ^5.4.0
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  lint: ^2.0.1
  lints: ^2.0.1
  mockito: ^5.3.2
  mocktail: ^0.3.0
  retrofit_generator: ^5.0.0+1
  test: ^1.22.1
