name: api

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  bloc: ^8.0.3
  freezed_annotation: 2.1.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  coverage: ^1.2.0
  freezed: 2.1.0+1
  lint: ^1.8.2
  mockito: ^5.1.0
  test: ^1.19.5
