include: package:lint/analysis_options.yaml

linter:
  rules:
    - sort_constructors_first
    - prefer_single_quotes

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - test/mocks.mocks.dart
