name: api
description: A new Flutter package project.
homepage: shtanko.dev

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  bloc: ^8.0.3
  collection: ^1.15.0
  freezed_annotation: 2.1.0
  http: ^0.13.4
  json_annotation: 4.6.0
  retrofit: 3.0.1+1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: 2.2.0
  coverage: ^1.2.0
  dart_code_metrics: ^4.14.0
  freezed: 2.1.0+1
  json_serializable: ^6.1.6
  lint: ^1.8.2
  mockito: ^5.1.0
  mocktail: ^0.3.0
  retrofit_generator: 4.0.3+1
  test: ^1.19.5
