name: api

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bloc: ^8.0.3
  freezed_annotation: 1.1.0
  json_annotation: ^4.4.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  coverage: ^1.2.0
  freezed: ">=1.0.0 <1.1.1"
  json_serializable: ^6.2.0
  lint: ^1.8.2
  mockito: ^5.1.0
  test: ^1.19.5
