name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]

jobs:
  test-app:
    name: App module job

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Download pub dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run Dart code metrics
        run: flutter pub run dart_code_metrics:metrics analyze lib

      - name: Run tests
        run: flutter test --coverage

#      - name: Install lcov
#        run: sudo apt-get install -y lcov
#
#      - name: Remove generated files from code coverage report
#        run: lcov --remove coverage/lcov.info 'lib/*/*.gen.dart' 'lib/generated/*.dart' 'lib/generated/*/*.dart' 'lib/di/*.dart' -o coverage/lcov.info
#
#      - name: Check Code Coverage
#        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
#        with:
#          path: coverage/lcov.info
#          min_coverage: 75
#          exclude: '**/*.g.dart **/*.gen.dart **/lib/di/ lib/generated/ **/lib/generated/ lib/di/*.dart'

  test-api:
    name: API logic module job

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Download pub dependencies
        run: flutter pub get

      - name: Pub Global
        run: dart pub global activate flutter_gen

      - name: Build runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Run fluttergen
        run: fluttergen -c pubspec.yaml

      - name: Run analyzer
        run: flutter analyze

      - name: Run Dart code metrics
        run: flutter pub run dart_code_metrics:metrics analyze lib

      - name: Run API tests
        run: flutter test --coverage

      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Remove generated files from code coverage report
        run: lcov --remove coverage/lcov.info 'lib/*/*.gen.dart' 'lib/generated/*.dart' 'lib/generated/*/*.dart' 'lib/di/*.dart' -o coverage/lcov.info

#      - name: Check Code Coverage
#        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
#        with:
#          path: coverage/lcov.info
#          min_coverage: 75
#          exclude: '**/*.g.dart **/*.gen.dart **/lib/di/ lib/generated/ **/lib/generated/ lib/di/*.dart'

  test-core:
    name: Core logic module job

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: core

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Download pub dependencies
        run: flutter pub get

      - name: Pub Global
        run: dart pub global activate flutter_gen

      - name: Build runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Run fluttergen
        run: fluttergen -c pubspec.yaml

      - name: Run analyzer
        run: flutter analyze

      - name: Run Dart code metrics
        run: flutter pub run dart_code_metrics:metrics analyze lib

      - name: Run API tests
        run: flutter test --coverage

#      - name: Install lcov
#        run: sudo apt-get install -y lcov
#
#      - name: Remove generated files from code coverage report
#        run: lcov --remove coverage/lcov.info 'lib/*/*.gen.dart' 'lib/generated/*.dart' 'lib/generated/*/*.dart' 'lib/di/*.dart' -o coverage/lcov.info
